version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aconselhamento_financeiro_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kiwi
      MYSQL_DATABASE: aconselhamento_financeiro
      MYSQL_USER: app_user
      MYSQL_PASSWORD: kiwi
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-kiwi"]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      timeout: 10s
      retries: 5
      interval: 30s
    networks:
      - app-network

  # Serviço opcional para interface web do Ollama
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama_webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
    volumes:
      - ollama_webui_data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  ollama_data:
    driver: local
  ollama_webui_data:
    driver: local

networks:
  app-network:
    driver: bridge